// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddCredentials(newAuthString: string): $CancellablePromise<void> {
    return $Call.ByID(4083250689, newAuthString);
}

export function GetConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(815152812).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveCredentials(email: string): $CancellablePromise<void> {
    return $Call.ByID(4243930372, email);
}

export function SetDeleteFromHost(deleteFromHost: boolean): $CancellablePromise<void> {
    return $Call.ByID(377345147, deleteFromHost);
}

export function SetDisableUnsupportedFilesFilter(disableUnsupportedFilesFilter: boolean): $CancellablePromise<void> {
    return $Call.ByID(821557574, disableUnsupportedFilesFilter);
}

export function SetForceUpload(forceUpload: boolean): $CancellablePromise<void> {
    return $Call.ByID(2189240988, forceUpload);
}

export function SetProxy(proxy: string): $CancellablePromise<void> {
    return $Call.ByID(2532528442, proxy);
}

export function SetRecursive(recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(455302378, recursive);
}

export function SetSaver(saver: boolean): $CancellablePromise<void> {
    return $Call.ByID(3030960747, saver);
}

export function SetSelected(email: string): $CancellablePromise<void> {
    return $Call.ByID(2816040807, email);
}

export function SetUploadThreads(uploadThreads: number): $CancellablePromise<void> {
    return $Call.ByID(1692245880, uploadThreads);
}

export function SetUseQuota(useQuota: boolean): $CancellablePromise<void> {
    return $Call.ByID(778544527, useQuota);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
