// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AlbumError represents an album creation error
 */
export class AlbumError {
    "AlbumName": string;
    "Error": string;

    /** Creates a new AlbumError instance. */
    constructor($$source: Partial<AlbumError> = {}) {
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumError instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumError($$parsedSource as Partial<AlbumError>);
    }
}

/**
 * AlbumStatus represents the status of album creation
 */
export class AlbumStatus {
    "AlbumName": string;
    "ItemsAdded": number;
    "TotalItems": number;
    "AlbumKeys": string[];
    "IsComplete": boolean;

    /** Creates a new AlbumStatus instance. */
    constructor($$source: Partial<AlbumStatus> = {}) {
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("ItemsAdded" in $$source)) {
            this["ItemsAdded"] = 0;
        }
        if (!("TotalItems" in $$source)) {
            this["TotalItems"] = 0;
        }
        if (!("AlbumKeys" in $$source)) {
            this["AlbumKeys"] = [];
        }
        if (!("IsComplete" in $$source)) {
            this["IsComplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AlbumKeys" in $$parsedSource) {
            $$parsedSource["AlbumKeys"] = $$createField3_0($$parsedSource["AlbumKeys"]);
        }
        return new AlbumStatus($$parsedSource as Partial<AlbumStatus>);
    }
}

export class Config {
    "credentials": string[];
    "selected": string;
    "proxy": string;
    "useQuota": boolean;
    "saver": boolean;
    "recursive": boolean;
    "forceUpload": boolean;
    "uploadThreads": number;
    "deleteFromHost": boolean;
    "disableUnsupportedFilesFilter": boolean;
    "albumName": string;
    "albumAutoMode": boolean;
    "setDateFromFilename": boolean;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("credentials" in $$source)) {
            this["credentials"] = [];
        }
        if (!("selected" in $$source)) {
            this["selected"] = "";
        }
        if (!("proxy" in $$source)) {
            this["proxy"] = "";
        }
        if (!("useQuota" in $$source)) {
            this["useQuota"] = false;
        }
        if (!("saver" in $$source)) {
            this["saver"] = false;
        }
        if (!("recursive" in $$source)) {
            this["recursive"] = false;
        }
        if (!("forceUpload" in $$source)) {
            this["forceUpload"] = false;
        }
        if (!("uploadThreads" in $$source)) {
            this["uploadThreads"] = 0;
        }
        if (!("deleteFromHost" in $$source)) {
            this["deleteFromHost"] = false;
        }
        if (!("disableUnsupportedFilesFilter" in $$source)) {
            this["disableUnsupportedFilesFilter"] = false;
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("albumAutoMode" in $$source)) {
            this["albumAutoMode"] = false;
        }
        if (!("setDateFromFilename" in $$source)) {
            this["setDateFromFilename"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credentials" in $$parsedSource) {
            $$parsedSource["credentials"] = $$createField0_0($$parsedSource["credentials"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class FileUploadResult {
    "MediaKey": string;
    "IsError": boolean;
    "Path": string;

    /** Creates a new FileUploadResult instance. */
    constructor($$source: Partial<FileUploadResult> = {}) {
        if (!("MediaKey" in $$source)) {
            this["MediaKey"] = "";
        }
        if (!("IsError" in $$source)) {
            this["IsError"] = false;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileUploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileUploadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileUploadResult($$parsedSource as Partial<FileUploadResult>);
    }
}

/**
 * FilesDroppedEvent is emitted when files are dropped on any drop zone
 */
export class FilesDroppedEvent {
    "files": string[];
    "dropZone": string;

    /** Creates a new FilesDroppedEvent instance. */
    constructor($$source: Partial<FilesDroppedEvent> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("dropZone" in $$source)) {
            this["dropZone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilesDroppedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FilesDroppedEvent {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new FilesDroppedEvent($$parsedSource as Partial<FilesDroppedEvent>);
    }
}

/**
 * StartUploadEvent is received from frontend to start upload
 */
export class StartUploadEvent {
    "files": string[];

    /** Creates a new StartUploadEvent instance. */
    constructor($$source: Partial<StartUploadEvent> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartUploadEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StartUploadEvent {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new StartUploadEvent($$parsedSource as Partial<StartUploadEvent>);
    }
}

export class ThreadStatus {
    "WorkerID": number;

    /**
     * "idle", "hashing", "checking", "uploading", "finalizing", "completed", "error"
     */
    "Status": string;
    "FilePath": string;
    "FileName": string;
    "Message": string;
    "BytesUploaded": number;
    "BytesTotal": number;

    /**
     * Current attempt number (1-based), 0 if not applicable
     */
    "Attempt": number;

    /** Creates a new ThreadStatus instance. */
    constructor($$source: Partial<ThreadStatus> = {}) {
        if (!("WorkerID" in $$source)) {
            this["WorkerID"] = 0;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("FilePath" in $$source)) {
            this["FilePath"] = "";
        }
        if (!("FileName" in $$source)) {
            this["FileName"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("BytesUploaded" in $$source)) {
            this["BytesUploaded"] = 0;
        }
        if (!("BytesTotal" in $$source)) {
            this["BytesTotal"] = 0;
        }
        if (!("Attempt" in $$source)) {
            this["Attempt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadStatus($$parsedSource as Partial<ThreadStatus>);
    }
}

export class UploadBatchStart {
    "Total": number;
    "TotalBytes": number;

    /** Creates a new UploadBatchStart instance. */
    constructor($$source: Partial<UploadBatchStart> = {}) {
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("TotalBytes" in $$source)) {
            this["TotalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadBatchStart instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadBatchStart {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadBatchStart($$parsedSource as Partial<UploadBatchStart>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
