//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../../../app/core/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "FileStatus": $$createType0,
        "ThreadStatus": $$createType1,
        "albumComplete": $$createType2,
        "albumError": $$createType3,
        "albumProgress": $$createType2,
        "files-dropped": $$createType4,
        "startUpload": $$createType5,
        "uploadStart": $$createType6,
        "uploadWarning": $$createType7,
    }));
}

// Private type creation functions
const $$createType0 = core$0.FileUploadResult.createFrom;
const $$createType1 = core$0.ThreadStatus.createFrom;
const $$createType2 = core$0.AlbumStatus.createFrom;
const $$createType3 = core$0.AlbumError.createFrom;
const $$createType4 = core$0.FilesDroppedEvent.createFrom;
const $$createType5 = core$0.StartUploadEvent.createFrom;
const $$createType6 = core$0.UploadBatchStart.createFrom;
const $$createType7 = core$0.PreflightWarning.createFrom;

configure();
