//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../../../../../app/backend/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "FileStatus": $$createType0,
        "ThreadStatus": $$createType1,
        "uploadStart": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = backend$0.FileUploadResult.createFrom;
const $$createType1 = backend$0.ThreadStatus.createFrom;
const $$createType2 = backend$0.UploadBatchStart.createFrom;

configure();
