// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as backend$0 from "../../../../../app/backend/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "FileStatus": backend$0.FileUploadResult;
            "ThreadStatus": backend$0.ThreadStatus;
            "albumComplete": backend$0.AlbumStatus;
            "albumProgress": backend$0.AlbumStatus;
            "uploadCancel": void;
            "uploadStart": backend$0.UploadBatchStart;
            "uploadStop": void;
            "uploadTotalBytes": number;
        }
    }
}
