// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as core$0 from "../../../../../app/core/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "FileStatus": core$0.FileUploadResult;
            "ThreadStatus": core$0.ThreadStatus;
            "albumComplete": core$0.AlbumStatus;
            "albumError": core$0.AlbumError;
            "albumProgress": core$0.AlbumStatus;
            "files-dropped": core$0.FilesDroppedEvent;
            "startUpload": core$0.StartUploadEvent;
            "uploadCancel": void;
            "uploadStart": core$0.UploadBatchStart;
            "uploadStop": void;
            "uploadTotalBytes": number;
            "uploadTotalBytesDelta": number;
            "uploadWarning": core$0.PreflightWarning;
        }
    }
}
