// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddCredentials(newAuthString: string): $CancellablePromise<void> {
    return $Call.ByID(3761332626, newAuthString);
}

/**
 * AddGoogleAccount exchanges an Embedded Setup oauth_token for a Google Photos
 * credential using the GUI's proxy preference, saves it, and returns the email.
 */
export function AddGoogleAccount(oauthToken: string): $CancellablePromise<string> {
    return $Call.ByID(1193706598, oauthToken);
}

export function AddTokenBindingAliasFromADB(email: string): $CancellablePromise<void> {
    return $Call.ByID(3043740547, email);
}

export function CredentialNeedsTokenBinding(authString: string): $CancellablePromise<boolean> {
    return $Call.ByID(3401558551, authString);
}

export function GetAccounts(): $CancellablePromise<$models.AccountsState> {
    return $Call.ByID(1187873763).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAlbumAutoMode(): $CancellablePromise<boolean> {
    return $Call.ByID(3034243646);
}

export function GetAlbumName(): $CancellablePromise<string> {
    return $Call.ByID(1570265661);
}

export function GetExcludePattern(): $CancellablePromise<string> {
    return $Call.ByID(913035763);
}

export function GetSettings(): $CancellablePromise<$models.Preferences> {
    return $Call.ByID(4032120730).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveCredentials(email: string): $CancellablePromise<void> {
    return $Call.ByID(741429753, email);
}

export function SetAlbumAutoMode(autoMode: boolean): $CancellablePromise<void> {
    return $Call.ByID(1875085042, autoMode);
}

export function SetAlbumName(albumName: string): $CancellablePromise<void> {
    return $Call.ByID(1670821521, albumName);
}

export function SetDeleteFromHost(deleteFromHost: boolean): $CancellablePromise<void> {
    return $Call.ByID(3351995250, deleteFromHost);
}

export function SetDisableUnsupportedFilesFilter(disableUnsupportedFilesFilter: boolean): $CancellablePromise<void> {
    return $Call.ByID(523767289, disableUnsupportedFilesFilter);
}

export function SetExcludePattern(pattern: string): $CancellablePromise<void> {
    return $Call.ByID(3232766647, pattern);
}

export function SetForceUpload(forceUpload: boolean): $CancellablePromise<void> {
    return $Call.ByID(700800787, forceUpload);
}

export function SetPairLivePhotos(pairLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(3112837812, pairLivePhotos);
}

export function SetProxy(proxy: string): $CancellablePromise<void> {
    return $Call.ByID(3453012749, proxy);
}

export function SetRecursive(recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(2974596005, recursive);
}

export function SetSaver(saver: boolean): $CancellablePromise<void> {
    return $Call.ByID(602728276, saver);
}

export function SetSelected(email: string): $CancellablePromise<void> {
    return $Call.ByID(2909725762, email);
}

export function SetSetDateFromFilename(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(2128354752, v);
}

export function SetSkipIncompleteLivePhotos(skipIncompleteLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(424242511, skipIncompleteLivePhotos);
}

export function SetUpdateExistingPhotosToLive(updateExistingPhotosToLive: boolean): $CancellablePromise<void> {
    return $Call.ByID(3924507429, updateExistingPhotosToLive);
}

export function SetUploadThreads(uploadThreads: number): $CancellablePromise<void> {
    return $Call.ByID(783059171, uploadThreads);
}

export function SetUseQuota(useQuota: boolean): $CancellablePromise<void> {
    return $Call.ByID(1540354890, useQuota);
}

// Private type creation functions
const $$createType0 = $models.AccountsState.createFrom;
const $$createType1 = $models.Preferences.createFrom;
