// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConfig($0: {}): Promise<$models.GlobalSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2320765359, $0) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SetPropxy(proxy: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1355477567, proxy) as any;
    return $resultPromise;
}

export function SetSelected(selected: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4003107648, selected) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.GlobalSettings.createFrom;
