// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class GlobalSettings {
    "credentials": string[];
    "selected": string;
    "proxy": string;
    "useQuota": boolean;
    "saver": boolean;
    "recursive": boolean;
    "forceUpload": boolean;
    "uploadThreads": number;
    "deleteFromHost": boolean;
    "disableUnsupportedFilesFilter": boolean;

    /** Creates a new GlobalSettings instance. */
    constructor($$source: Partial<GlobalSettings> = {}) {
        if (!("credentials" in $$source)) {
            this["credentials"] = [];
        }
        if (!("selected" in $$source)) {
            this["selected"] = "";
        }
        if (!("proxy" in $$source)) {
            this["proxy"] = "";
        }
        if (!("useQuota" in $$source)) {
            this["useQuota"] = false;
        }
        if (!("saver" in $$source)) {
            this["saver"] = false;
        }
        if (!("recursive" in $$source)) {
            this["recursive"] = false;
        }
        if (!("forceUpload" in $$source)) {
            this["forceUpload"] = false;
        }
        if (!("uploadThreads" in $$source)) {
            this["uploadThreads"] = 0;
        }
        if (!("deleteFromHost" in $$source)) {
            this["deleteFromHost"] = false;
        }
        if (!("disableUnsupportedFilesFilter" in $$source)) {
            this["disableUnsupportedFilesFilter"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalSettings {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credentials" in $$parsedSource) {
            $$parsedSource["credentials"] = $$createField0_0($$parsedSource["credentials"]);
        }
        return new GlobalSettings($$parsedSource as Partial<GlobalSettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
